-- actualizando catalogo a ingles nuevamente
UPDATE public.account_account SET "name"='Current Assets' WHERE code='101000';
UPDATE public.account_account SET "name"='Account Receivable (PoS)' WHERE code='101300';
UPDATE public.account_account SET "name"='Transitory Account' WHERE code='101401';
UPDATE public.account_account SET "name"='Pending receipts' WHERE code='101402';
UPDATE public.account_account SET "name"='Pending payments' WHERE code='101403';
UPDATE public.account_account SET "name"='Bank' WHERE code='101404';
UPDATE public.account_account SET "name"='Cash' WHERE code='101501';
UPDATE public.account_account SET "name"='Transfer of liquidity' WHERE code='101701';
UPDATE public.account_account SET "name"='Stock Valuation' WHERE code='110100';
UPDATE public.account_account SET "name"='Stock Interim (Received)' WHERE code='110200';
UPDATE public.account_account SET "name"='Stock Interim (Delivered)' WHERE code='110300';
UPDATE public.account_account SET "name"='Account Receivable' WHERE code='121000';
UPDATE public.account_account SET "name"='Products to receive' WHERE code='121100';
UPDATE public.account_account SET "name"='Tax Paid' WHERE code='131000';
UPDATE public.account_account SET "name"='Tax Receivable' WHERE code='132000';
UPDATE public.account_account SET "name"='Prepayments' WHERE code='141000';
UPDATE public.account_account SET "name"='Fixed Asset' WHERE code='151000';
UPDATE public.account_account SET "name"='Non-current assets' WHERE code='191000';
UPDATE public.account_account SET "name"='Current Liabilities' WHERE code='201000';
UPDATE public.account_account SET "name"='Account Payable' WHERE code='211000';
UPDATE public.account_account SET "name"='Bills to receive' WHERE code='211100';
UPDATE public.account_account SET "name"='Tax Received' WHERE code='251000';
UPDATE public.account_account SET "name"='Tax Payable' WHERE code='252000';
UPDATE public.account_account SET "name"='Non-current Liabilities' WHERE code='291000';
UPDATE public.account_account SET "name"='Capital' WHERE code='301000';
UPDATE public.account_account SET "name"='Dividens' WHERE code='302000';
UPDATE public.account_account SET "name"='Product Sales' WHERE code='400000';
UPDATE public.account_account SET "name"='Foreign Exchange Gain' WHERE code='441000';
UPDATE public.account_account SET "name"='Cash Difference Gain' WHERE code='442000';
UPDATE public.account_account SET "name"='Cash Discount Gain' WHERE code='443000';
UPDATE public.account_account SET "name"='Other Income' WHERE code='450000';
UPDATE public.account_account SET "name"='Cost of Goods Sold' WHERE code='500000';
UPDATE public.account_account SET "name"='Expenses' WHERE code='600000';
UPDATE public.account_account SET "name"='Purchase of Equipments' WHERE code='611000';
UPDATE public.account_account SET "name"='Rent' WHERE code='612000';
UPDATE public.account_account SET "name"='Bank Fees' WHERE code='620000';
UPDATE public.account_account SET "name"='Salary Expenses' WHERE code='630000';
UPDATE public.account_account SET "name"='Foreign Exchange Loss' WHERE code='641000';
UPDATE public.account_account SET "name"='Cash Difference Loss' WHERE code='642000';
UPDATE public.account_account SET "name"='Cash Discount Loss' WHERE code='643000';
UPDATE public.account_account SET "name"='RD Expenses' WHERE code='961000';
UPDATE public.account_account SET "name"='Sales Expenses' WHERE code='962000';
UPDATE public.account_account SET "name"='Undistributed profits/losses' WHERE code='999999';
